Repository fmcubium/Starcrosser, pull requests merged in 2024-12, with the labels that each got.

#4 Created graph class declaration
  .gitignore
  main.cpp
  model/Graph.cpp
  model/Graph.h
Labels: enhancement, 📊 Model

#8 First Inclusion of WIP StarCrosser UI files
  starcrosser_ui/CMakeLists.txt
  starcrosser_ui/CMakeLists.txt.user
  starcrosser_ui/Milky_Way_Galaxy.jpg
  starcrosser_ui/Resources.qrc
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeCache.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeCache.txt.prev
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CMakeCXXCompiler.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CMakeDetermineCompilerABI_CXX.bin
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CMakeRCCompiler.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CMakeSystem.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CompilerIdCXX/a.exe
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/CMakeConfigureLog.yaml
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/TargetDirectories.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/clean_additional.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/cmake.check_cache
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/rules.ninja
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui.dir/main.cpp.obj
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui.dir/mainwindow.cpp.obj
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui.dir/reportwindow.cpp.obj
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui.dir/starcrosser_ui_autogen/EWIEGA46WW/qrc_Resources.cpp.obj
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui.dir/starcrosser_ui_autogen/mocs_compilation.cpp.obj
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutoRcc_Resources_EWIEGA46WW_Info.json
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutoRcc_Resources_EWIEGA46WW_Lock.lock
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutoRcc_Resources_EWIEGA46WW_Used.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutogenInfo.json
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutogenUsed.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/ParseCache.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/Testing/Temporary/LastTest.log
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/build.ninja
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/cmake_install.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/qtcsettings.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui.exe
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/EWIEGA46WW/moc_mainwindow.cpp
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/EWIEGA46WW/moc_mainwindow.cpp.d
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/EWIEGA46WW/moc_reportwindow.cpp
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/EWIEGA46WW/moc_reportwindow.cpp.d
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/EWIEGA46WW/qrc_Resources.cpp
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/deps
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/include/ui_mainwindow.h
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/include/ui_reportwindow.h
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/moc_predefs.h
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/mocs_compilation.cpp
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/timestamp
  starcrosser_ui/main.cpp
  starcrosser_ui/mainwindow.cpp
  starcrosser_ui/mainwindow.h
  starcrosser_ui/mainwindow.ui
  starcrosser_ui/mainwindow.ui.autosave
  starcrosser_ui/reportwindow.cpp
  starcrosser_ui/reportwindow.h
  starcrosser_ui/reportwindow.ui
Labels: enhancement, 📺 View

#13 Created util, implemented Dijkstra's
  .gitignore
  Util.cpp
  Util.h
  main.cpp
Labels: enhancement, 🎮 Controller

#12 Final UI Design
  .qtcreator/project.json
  .qtcreator/project.json.user
  starcrosser_ui/CMakeLists.txt.user
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutoRcc_Resources_EWIEGA46WW_Info.json
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutoRcc_Resources_EWIEGA46WW_Used.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutogenInfo.json
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/starcrosser_ui_autogen.dir/AutogenUsed.txt
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/qtcsettings.cmake
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/deps
  starcrosser_ui/build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/starcrosser_ui_autogen/mocs_compilation.cpp
  starcrosser_ui/mainwindow.ui
  starcrosser_ui/mainwindow.ui.autosave
Labels: enhancement, 📺 View

#21 Completed algorithm implementations
  starcrosser_ui/controller/Util.cpp
  starcrosser_ui/controller/Util.h
  starcrosser_ui/model/Graph.cpp
  starcrosser_ui/model/Graph.h
Labels: enhancement, 📊 Model, 🎮 Controller

#22 Bug fixes
  main.cpp
  starcrosser_ui/main.cpp
  starcrosser_ui/model/Graph.cpp
  starcrosser_ui/model/Graph.h
Labels: bug
